name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev unzip openjdk-17-jdk
        pip install buildozer cython

    - name: Install Android SDK
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools/latest
        mv $HOME/android-sdk/cmdline-tools/latest/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-33" "build-tools;33.0.0" "platform-tools"

    - name: Install Android NDK
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip android-ndk-r21e-linux-x86_64.zip -d $HOME
        export ANDROID_NDK_HOME=$HOME/android-ndk-r21e

    - name: Set up Buildozer environment
      run: |
        # Create Buildozer's expected SDK directory structure
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/build-tools/33.0.0
        # Symlink the entire SDK
        ln -s $ANDROID_HOME $HOME/.buildozer/android/platform/android-sdk
        # Symlink build-tools
        ln -s $ANDROID_HOME/build-tools/33.0.0 $HOME/.buildozer/android/platform/android-sdk/build-tools/33.0.0
        # Symlink sdkmanager to the expected location
        ln -s $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
        # Set environment variables for Buildozer
        export ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk
        export ANDROIDNDK=$ANDROID_NDK_HOME

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk
